import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Shield, Zap, Brain, Activity, Lock, Users, ArrowRight, Server, ChevronRight } from 'lucide-react';
import heroBg from '../assets/hero_bg.png';

export default function LandingPage() {
  const features = [
    {
      icon: <Activity size={32} color="var(--accent-cyan)" />,
      title: 'Real-Time Telemetry',
      desc: 'Microsecond-latency packet inspection capturing complex network flows.',
    },
    {
      icon: <Brain size={32} color="var(--accent-purple)" />,
      title: 'AI Threat Detection',
      desc: 'Machine learning ensemble models accurately classifying zero-day anomalies.',
    },
    {
      icon: <Zap size={32} color="var(--accent-orange)" />,
      title: 'LLM Analysis',
      desc: 'Context-aware threat intelligence generated by advanced language models.',
    },
    {
      icon: <Lock size={32} color="var(--accent-red)" />,
      title: 'Active Defense',
      desc: 'Automated mitigation and IP blocking deployed at the network edge.',
    },
  ];

  const team = [
    { name: 'Student 1', role: 'AI / ML Engineer', icon: '🧠' },
    { name: 'Student 2', role: 'Network Security', icon: '🛡️' },
    { name: 'Student 3', role: 'Backend Architecture', icon: '⚙️' },
    { name: 'Student 4', role: 'Frontend & UI/UX', icon: '💻' },
    { name: 'Student 5', role: 'DevOps & Cloud', icon: '☁️' },
  ];

  return (
    <div style={{ backgroundColor: 'var(--bg-base)', minHeight: '100vh', color: 'var(--text-primary)' }}>
      {/* Navbar */}
      <nav style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1.5rem 5%', position: 'absolute', top: 0, width: '100%', zIndex: 50 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <Shield color="var(--accent-cyan)" size={32} style={{ filter: 'drop-shadow(0 0 10px rgba(0, 242, 254, 0.5))' }} />
          <span style={{ fontSize: '1.5rem', fontWeight: '800', letterSpacing: '1px' }}>SecureNet SOC</span>
        </div>
        <div style={{ display: 'flex', gap: '1.5rem', alignItems: 'center' }}>
          <a href="#features" style={{ color: 'var(--text-secondary)', fontWeight: '500', transition: 'color 0.2s' }}>Features</a>
          <a href="#architecture" style={{ color: 'var(--text-secondary)', fontWeight: '500', transition: 'color 0.2s' }}>Architecture</a>
          <a href="#team" style={{ color: 'var(--text-secondary)', fontWeight: '500', transition: 'color 0.2s' }}>Team</a>
          <Link to="/login" style={{ 
            background: 'var(--accent-cyan-dim)', 
            color: 'var(--accent-cyan)', 
            padding: '0.5rem 1.5rem', 
            borderRadius: '999px',
            border: '1px solid var(--accent-cyan)',
            fontWeight: '600'
          }}>
            System Login
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <section style={{ 
        position: 'relative', 
        height: '100vh', 
        display: 'flex', 
        alignItems: 'center', 
        justifyContent: 'center',
        overflow: 'hidden'
      }}>
        {/* Background Image with Overlay */}
        <div style={{ 
          position: 'absolute', 
          top: 0, left: 0, right: 0, bottom: 0,
          backgroundImage: `url(${heroBg})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          opacity: 0.3,
          zIndex: 0
        }} />
        <div style={{ 
          position: 'absolute', 
          top: 0, left: 0, right: 0, bottom: 0,
          background: 'linear-gradient(to bottom, transparent 0%, var(--bg-base) 100%)',
          zIndex: 1
        }} />

        <div style={{ position: 'relative', zIndex: 10, textAlign: 'center', maxWidth: '800px', padding: '0 2rem' }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <span style={{ 
              display: 'inline-block', 
              padding: '0.5rem 1rem', 
              background: 'rgba(168, 85, 247, 0.1)', 
              border: '1px solid rgba(168, 85, 247, 0.3)', 
              color: 'var(--accent-purple)', 
              borderRadius: '999px',
              fontWeight: '600',
              marginBottom: '1.5rem',
              letterSpacing: '1px'
            }}>
              GRADUATION PROJECT 2026
            </span>
            <h1 style={{ 
              fontSize: '4.5rem', 
              lineHeight: '1.1', 
              marginBottom: '1.5rem',
              background: 'linear-gradient(135deg, #fff 0%, #a5b4fc 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              filter: 'drop-shadow(0 0 30px rgba(168, 85, 247, 0.2))'
            }}>
              Next-Gen Security <br/> Operations Center
            </h1>
            <p style={{ fontSize: '1.25rem', color: 'var(--text-secondary)', marginBottom: '2.5rem', lineHeight: '1.6' }}>
              An AI-powered Intrusion Detection System built from the ground up. 
              Combining Machine Learning, Large Language Models, and Real-Time Networking.
            </p>
            
            <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center' }}>
              <Link to="/login" style={{ 
                display: 'flex', alignItems: 'center', gap: '0.5rem',
                background: 'var(--accent-cyan)', 
                color: '#000', 
                padding: '1rem 2rem', 
                borderRadius: '8px',
                fontWeight: '700',
                fontSize: '1.1rem',
                boxShadow: '0 0 20px var(--accent-cyan-glow)',
                transition: 'all 0.3s ease'
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.transform = 'translateY(-2px)';
                e.currentTarget.style.boxShadow = '0 0 30px var(--accent-cyan-glow)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = 'translateY(0)';
                e.currentTarget.style.boxShadow = '0 0 20px var(--accent-cyan-glow)';
              }}>
                Access SOC Dashboard <ArrowRight size={20} />
              </Link>
              <a href="#architecture" style={{ 
                display: 'flex', alignItems: 'center', gap: '0.5rem',
                background: 'rgba(255, 255, 255, 0.05)', 
                color: '#fff', 
                padding: '1rem 2rem', 
                borderRadius: '8px',
                border: '1px solid rgba(255, 255, 255, 0.1)',
                fontWeight: '600',
                fontSize: '1.1rem'
              }}>
                View Architecture
              </a>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" style={{ padding: '8rem 5%', position: 'relative' }}>
        <div style={{ textAlign: 'center', marginBottom: '5rem' }}>
          <h2 style={{ fontSize: '3rem', marginBottom: '1rem' }}>System Capabilities</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '1.2rem', maxWidth: '600px', margin: '0 auto' }}>
            A unified pipeline bridging the gap between raw network telemetry and actionable cyber intelligence.
          </p>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '2rem', maxWidth: '1200px', margin: '0 auto' }}>
          {features.map((f, i) => (
            <motion.div 
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              whileHover={{ y: -5, boxShadow: `0 10px 30px -10px ${f.icon.props.color}` }}
              transition={{ delay: i * 0.1, duration: 0.3 }}
              viewport={{ once: true }}
              style={{
                background: 'rgba(10, 15, 28, 0.6)',
                border: '1px solid var(--border-color)',
                padding: '2.5rem',
                borderRadius: '16px',
                backdropFilter: 'blur(20px)',
                position: 'relative',
                overflow: 'hidden',
                transition: 'border-color 0.3s ease'
              }}
              onMouseEnter={(e) => e.currentTarget.style.borderColor = f.icon.props.color}
              onMouseLeave={(e) => e.currentTarget.style.borderColor = 'var(--border-color)'}
            >
              <div style={{ 
                position: 'absolute', top: 0, left: 0, width: '100%', height: '4px',
                background: `linear-gradient(90deg, ${f.icon.props.color}, transparent)`
              }} />
              <div style={{ marginBottom: '1.5rem', background: 'rgba(255,255,255,0.03)', display: 'inline-block', padding: '1rem', borderRadius: '12px' }}>
                {f.icon}
              </div>
              <h3 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>{f.title}</h3>
              <p style={{ color: 'var(--text-secondary)', lineHeight: '1.6' }}>{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Architecture Section */}
      <section id="architecture" style={{ padding: '5rem 5%', background: 'rgba(0,0,0,0.3)', borderTop: '1px solid var(--border-color)', borderBottom: '1px solid var(--border-color)' }}>
        <div style={{ maxWidth: '1200px', margin: '0 auto', textAlign: 'center' }}>
          <h2 style={{ fontSize: '3rem', marginBottom: '4rem' }}>Microservices Architecture</h2>
          
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' }}>
            {['Network Sniffer', 'Feature Extractor', 'ML Engine', 'LLM Analyzer', 'Firewall Control'].map((node, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                <div style={{
                  background: 'rgba(17,24,39,0.8)',
                  border: `1px solid ${i === 2 ? 'var(--accent-cyan)' : 'var(--border-highlight)'}`,
                  padding: '1.5rem',
                  borderRadius: '12px',
                  boxShadow: i === 2 ? '0 0 20px rgba(0, 242, 254, 0.2)' : 'none',
                  minWidth: '160px'
                }}>
                  <Server size={24} color={i === 2 ? 'var(--accent-cyan)' : 'var(--text-secondary)'} style={{ marginBottom: '0.5rem' }} />
                  <p style={{ margin: 0, fontWeight: '600', fontSize: '0.9rem' }}>{node}</p>
                </div>
                {i < 4 && <ChevronRight size={32} color="var(--text-muted)" />}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Team Section */}
      <section id="team" style={{ padding: '8rem 5%' }}>
        <div style={{ textAlign: 'center', marginBottom: '5rem' }}>
          <Users size={48} color="var(--accent-purple)" style={{ marginBottom: '1rem' }} />
          <h2 style={{ fontSize: '3rem', marginBottom: '1rem' }}>Development Team</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '1.2rem' }}>Graduation Project Class of 2026</p>
        </div>

        <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: '2rem', maxWidth: '1200px', margin: '0 auto' }}>
          {team.map((member, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, scale: 0.9 }}
              whileInView={{ opacity: 1, scale: 1 }}
              transition={{ delay: i * 0.1 }}
              viewport={{ once: true }}
              style={{
                background: 'rgba(17, 24, 39, 0.6)',
                border: '1px solid var(--border-color)',
                padding: '2rem',
                borderRadius: '16px',
                textAlign: 'center',
                width: '200px',
                backdropFilter: 'blur(10px)'
              }}
            >
              <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>{member.icon}</div>
              <h4 style={{ fontSize: '1.2rem', marginBottom: '0.5rem' }}>{member.name}</h4>
              <p style={{ color: 'var(--accent-cyan)', fontSize: '0.85rem', fontWeight: '600', textTransform: 'uppercase' }}>{member.role}</p>
            </motion.div>
          ))}
        </div>
      </section>

      <footer style={{ borderTop: '1px solid var(--border-color)', padding: '2rem 5%', textAlign: 'center', color: 'var(--text-muted)' }}>
        <p>© 2026 SecureNet SOC Team. Graduation Project.</p>
      </footer>
    </div>
  );
}
